import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Character } from '../../components/character/character';
import { AnimationData, AnimationName, CharacterVoices, SpecialMove } from '../../models/character';
import { PowerWave } from '../../projectiles/power-wave/power-wave';
import { Hat, HAT_FLIGHT_MS } from '../../projectiles/hat/hat';
import {
  BURNING_KNUCKLE_FRAMES,
  CRACK_SHOOT_FRAMES,
  POWER_WAVE_FRAMES,
  RISING_TACKLE_FRAMES,
} from './terry-specials';
import { withDurations } from '../../helpers/special-frame';

/** Terry Bogard — concrete Character subclass. */
@Component({
  selector: 'app-terry',
  templateUrl: '../../components/character/character.html',
  styleUrl: './terry.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Terry extends Character {
  protected override readonly voices: CharacterVoices = {
    lightPunch: 'assets/sfx/terry/terry-light-punch.mp3',
    heavyPunch: 'assets/sfx/terry/terry-heavy-punch.mp3',
    lightKick: 'assets/sfx/terry/terry-light-punch.mp3',
    heavyKick: 'assets/sfx/terry/terry-heavy-punch.mp3',
    taunt: 'assets/sfx/terry/terry-taunt.mp3',
    lightPunchWhiff: 'assets/sfx/misc/light-punch-whiff.mp3',
    heavyPunchWhiff: 'assets/sfx/misc/heavy-punch-whiff.mp3',
    lightKickWhiff: 'assets/sfx/misc/light-punch-whiff.mp3',
    heavyKickWhiff: 'assets/sfx/misc/heavy-punch-whiff.mp3',
    jump: 'assets/sfx/misc/jump.mp3',
  };

  protected override readonly animationFrames: Partial<Record<AnimationName, AnimationData>> = {
    idle: {
      loop: true,
      bounce: true,
      frames: [
        {
          src: 'assets/img/characters/terry/idle/0.png',
          w: 64,
          h: 107,
          anchorX: 31,
          anchorY: 100,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/terry/idle/1.png',
          w: 64,
          h: 107,
          anchorX: 31,
          anchorY: 100,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/terry/idle/2.png',
          w: 65,
          h: 107,
          anchorX: 31,
          anchorY: 100,
          durationMs: 150,
        },
      ],
    },
    forward: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/terry/walk/0.png',
          w: 69,
          h: 103,
          anchorX: 34,
          anchorY: 102,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/terry/walk/1.png',
          w: 63,
          h: 103,
          anchorX: 31,
          anchorY: 102,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/terry/walk/2.png',
          w: 61,
          h: 103,
          anchorX: 30,
          anchorY: 102,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/terry/walk/3.png',
          w: 58,
          h: 103,
          anchorX: 29,
          anchorY: 102,
          durationMs: 175,
        },
      ],
    },
    backwards: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/terry/backwards/0.png',
          w: 62,
          h: 105,
          anchorX: 31,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/terry/backwards/1.png',
          w: 65,
          h: 105,
          anchorX: 32,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/terry/backwards/2.png',
          w: 59,
          h: 105,
          anchorX: 29,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/terry/backwards/3.png',
          w: 62,
          h: 105,
          anchorX: 31,
          anchorY: 104,
          durationMs: 175,
        },
      ],
    },
    backstep: {
      frames: [
        {
          src: 'assets/img/characters/terry/backstep/0.png',
          w: 73,
          h: 92,
          anchorX: 29,
          anchorY: 91,
          durationMs: 380,
        },
        {
          src: 'assets/img/characters/terry/backstep/1.png',
          w: 57,
          h: 92,
          anchorX: 31,
          anchorY: 91,
          durationMs: 70,
        },
      ],
    },
    crouch: {
      frames: [
        {
          src: 'assets/img/characters/terry/crouch/0.png',
          w: 56,
          h: 87,
          anchorX: 27,
          anchorY: 79,
          durationMs: 45,
        },
        {
          src: 'assets/img/characters/terry/crouch/1.png',
          w: 58,
          h: 87,
          anchorX: 29,
          anchorY: 80,
          durationMs: 150,
        },
      ],
    },
    crouchStill: {
      frames: [
        {
          src: 'assets/img/characters/terry/crouch/1.png',
          w: 58,
          h: 87,
          anchorX: 29,
          anchorY: 80,
          durationMs: 1000,
        },
      ],
    },
    crouchForward: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/terry/crouch-forward/0.png',
          w: 53,
          h: 77,
          anchorX: 30,
          anchorY: 76,
          durationMs: 117,
        },
        {
          src: 'assets/img/characters/terry/crouch-forward/1.png',
          w: 52,
          h: 77,
          anchorX: 26,
          anchorY: 76,
          durationMs: 117,
        },
        {
          src: 'assets/img/characters/terry/crouch-forward/2.png',
          w: 55,
          h: 77,
          anchorX: 27,
          anchorY: 76,
          durationMs: 117,
        },
        {
          src: 'assets/img/characters/terry/crouch-forward/3.png',
          w: 61,
          h: 77,
          anchorX: 30,
          anchorY: 76,
          durationMs: 117,
        },
        {
          src: 'assets/img/characters/terry/crouch-forward/4.png',
          w: 55,
          h: 77,
          anchorX: 27,
          anchorY: 76,
          durationMs: 117,
        },
        {
          src: 'assets/img/characters/terry/crouch-forward/5.png',
          w: 52,
          h: 77,
          anchorX: 26,
          anchorY: 76,
          durationMs: 117,
        },
      ],
    },
    crouchLightPunch: {
      frames: [
        {
          src: 'assets/img/characters/terry/crouch-light-punch/0.png',
          w: 61,
          h: 70,
          anchorX: 28,
          anchorY: 63,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/terry/crouch-light-punch/1.png',
          w: 88,
          h: 70,
          anchorX: 28,
          anchorY: 63,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/terry/crouch-light-punch/2.png',
          w: 62,
          h: 70,
          anchorX: 28,
          anchorY: 64,
          durationMs: 50,
        },
      ],
    },
    crouchHeavyPunch: {
      frames: [
        {
          src: 'assets/img/characters/terry/crouch-heavy-punch/0.png',
          w: 61,
          h: 72,
          anchorX: 28,
          anchorY: 65,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-punch/1.png',
          w: 61,
          h: 72,
          anchorX: 29,
          anchorY: 65,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-punch/2.png',
          w: 97,
          h: 72,
          anchorX: 29,
          anchorY: 65,
          durationMs: 180,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-punch/3.png',
          w: 61,
          h: 72,
          anchorX: 29,
          anchorY: 65,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-punch/4.png',
          w: 62,
          h: 72,
          anchorX: 29,
          anchorY: 65,
          durationMs: 60,
        },
      ],
    },
    crouchLightKick: {
      frames: [
        {
          src: 'assets/img/characters/terry/crouch-light-kick/0.png',
          w: 56,
          h: 68,
          anchorX: 27,
          anchorY: 67,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/terry/crouch-light-kick/1.png',
          w: 71,
          h: 68,
          anchorX: 25,
          anchorY: 67,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/terry/crouch-light-kick/2.png',
          w: 102,
          h: 68,
          anchorX: 24,
          anchorY: 67,
          durationMs: 140,
        },
        {
          src: 'assets/img/characters/terry/crouch-light-kick/3.png',
          w: 71,
          h: 68,
          anchorX: 25,
          anchorY: 67,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/terry/crouch-light-kick/4.png',
          w: 57,
          h: 68,
          anchorX: 28,
          anchorY: 67,
          durationMs: 40,
        },
      ],
    },
    crouchHeavyKick: {
      frames: [
        {
          src: 'assets/img/characters/terry/crouch-heavy-kick/0.png',
          w: 55,
          h: 72,
          anchorX: 27,
          anchorY: 71,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-kick/1.png',
          w: 69,
          h: 72,
          anchorX: 34,
          anchorY: 71,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-kick/2.png',
          w: 116,
          h: 72,
          anchorX: 25,
          anchorY: 71,
          durationMs: 280,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-kick/3.png',
          w: 67,
          h: 72,
          anchorX: 32,
          anchorY: 71,
          durationMs: 120,
        },
        {
          src: 'assets/img/characters/terry/crouch-heavy-kick/4.png',
          w: 52,
          h: 72,
          anchorX: 25,
          anchorY: 71,
          durationMs: 160,
        },
      ],
    },
    jumpUp: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump/0.png',
          w: 68,
          h: 136,
          anchorX: 31,
          anchorY: 135,
          durationMs: 167,
        },
        {
          src: 'assets/img/characters/terry/jump/1.png',
          w: 68,
          h: 136,
          anchorX: 31,
          anchorY: 135,
          durationMs: 167,
        },
        {
          src: 'assets/img/characters/terry/jump/2.png',
          w: 68,
          h: 136,
          anchorX: 32,
          anchorY: 135,
          durationMs: 167,
        },
      ],
    },
    jumpFall: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump/3.png',
          w: 68,
          h: 136,
          anchorX: 34,
          anchorY: 135,
          durationMs: 167,
        },
        {
          src: 'assets/img/characters/terry/jump/4.png',
          w: 68,
          h: 136,
          anchorX: 37,
          anchorY: 135,
          durationMs: 167,
        },
      ],
    },
    jumpGround: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump/5.png',
          w: 69,
          h: 136,
          anchorX: 42,
          anchorY: 135,
          durationMs: 200,
        },
      ],
    },
    jumpForward: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump-forward/0.png',
          w: 56,
          h: 136,
          anchorX: 30,
          anchorY: 135,
          durationMs: 110,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/1.png',
          w: 68,
          h: 136,
          anchorX: 45,
          anchorY: 135,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/2.png',
          w: 80,
          h: 136,
          anchorX: 40,
          anchorY: 135,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/3.png',
          w: 59,
          h: 136,
          anchorX: 29,
          anchorY: 135,
          durationMs: 60,
        },
      ],
    },
    jumpForwardFall: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump-forward/4.png',
          w: 80,
          h: 136,
          anchorX: 40,
          anchorY: 135,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/5.png',
          w: 60,
          h: 136,
          anchorX: 30,
          anchorY: 135,
          durationMs: 220,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/6.png',
          w: 57,
          h: 136,
          anchorX: 28,
          anchorY: 135,
          durationMs: 240,
        },
      ],
    },
    jumpBackward: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump-backward/0.png',
          w: 56,
          h: 105,
          anchorX: 30,
          anchorY: 104,
          durationMs: 167,
        },
        {
          src: 'assets/img/characters/terry/jump-backward/1.png',
          w: 80,
          h: 105,
          anchorX: 40,
          anchorY: 104,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/jump-backward/2.png',
          w: 59,
          h: 105,
          anchorX: 29,
          anchorY: 104,
          durationMs: 60,
        },
      ],
    },
    jumpBackwardFall: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump-backward/3.png',
          w: 80,
          h: 105,
          anchorX: 40,
          anchorY: 104,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/jump-backward/4.png',
          w: 68,
          h: 105,
          anchorX: 43,
          anchorY: 104,
          durationMs: 167,
        },
      ],
    },
    airHeavyRecover: {
      frames: [
        {
          src: 'assets/img/characters/terry/jump-forward/5.png',
          w: 60,
          h: 136,
          anchorX: 30,
          anchorY: 135,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/6.png',
          w: 57,
          h: 136,
          anchorX: 28,
          anchorY: 135,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/terry/jump-forward/7.png',
          w: 57,
          h: 136,
          anchorX: 31,
          anchorY: 135,
          durationMs: 1500,
        },
      ],
    },
    airHeavyPunch: {
      frames: [
        {
          src: 'assets/img/characters/terry/air-heavy-punch/0.png',
          w: 55,
          h: 85,
          anchorX: 26,
          anchorY: 84,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/air-heavy-punch/1.png',
          w: 54,
          h: 85,
          anchorX: 31,
          anchorY: 84,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/air-heavy-punch/2.png',
          w: 85,
          h: 85,
          anchorX: 28,
          anchorY: 84,
          durationMs: 150,
        },
      ],
    },
    airLightPunch: {
      frames: [
        {
          src: 'assets/img/characters/terry/air-light-punch/0.png',
          w: 53,
          h: 104,
          anchorX: 26,
          anchorY: 103,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/air-light-punch/1.png',
          w: 64,
          h: 104,
          anchorX: 30,
          anchorY: 103,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/terry/air-light-punch/2.png',
          w: 88,
          h: 104,
          anchorX: 28,
          anchorY: 103,
          durationMs: 2000,
        },
      ],
    },
    airLightKick: {
      frames: [
        {
          src: 'assets/img/characters/terry/air-kick/0.png',
          w: 53,
          h: 84,
          anchorX: 26,
          anchorY: 83,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/terry/air-kick/1.png',
          w: 64,
          h: 84,
          anchorX: 32,
          anchorY: 83,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/air-kick/2.png',
          w: 102,
          h: 84,
          anchorX: 28,
          anchorY: 83,
          durationMs: 2000,
        },
      ],
    },
    airLightKickUp: {
      frames: [
        {
          src: 'assets/img/characters/terry/air-kick-up-light/0.png',
          w: 53,
          h: 98,
          anchorX: 26,
          anchorY: 97,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-light/1.png',
          w: 60,
          h: 98,
          anchorX: 30,
          anchorY: 97,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-light/2.png',
          w: 84,
          h: 98,
          anchorX: 28,
          anchorY: 97,
          durationMs: 2000,
        },
      ],
    },
    airHeavyKickUp: {
      frames: [
        {
          src: 'assets/img/characters/terry/air-kick-up-heavy/0.png',
          w: 63,
          h: 107,
          anchorX: 32,
          anchorY: 106,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-heavy/1.png',
          w: 53,
          h: 107,
          anchorX: 28,
          anchorY: 106,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-heavy/2.png',
          w: 46,
          h: 107,
          anchorX: 23,
          anchorY: 106,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-heavy/3.png',
          w: 66,
          h: 107,
          anchorX: 24,
          anchorY: 106,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-heavy/4.png',
          w: 108,
          h: 107,
          anchorX: 25,
          anchorY: 106,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/terry/air-kick-up-heavy/5.png',
          w: 50,
          h: 107,
          anchorX: 25,
          anchorY: 106,
          durationMs: 90,
        },
      ],
    },
    airHeavyKick: {
      frames: [
        {
          src: 'assets/img/characters/terry/air-kick/0.png',
          w: 53,
          h: 84,
          anchorX: 26,
          anchorY: 83,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/air-kick/1.png',
          w: 64,
          h: 84,
          anchorX: 32,
          anchorY: 83,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/air-kick/2.png',
          w: 102,
          h: 84,
          anchorX: 28,
          anchorY: 83,
          durationMs: 150,
        },
      ],
    },
    lightPunch: {
      frames: [
        {
          src: 'assets/img/characters/terry/light-punch/0.png',
          w: 66,
          h: 101,
          anchorX: 32,
          anchorY: 93,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/terry/light-punch/1.png',
          w: 89,
          h: 101,
          anchorX: 32,
          anchorY: 93,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/terry/light-punch/2.png',
          w: 66,
          h: 101,
          anchorX: 32,
          anchorY: 93,
          durationMs: 50,
        },
      ],
    },
    heavyPunch: {
      frames: [
        {
          src: 'assets/img/characters/terry/heavy-punch/0.png',
          w: 66,
          h: 105,
          anchorX: 32,
          anchorY: 97,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/heavy-punch/1.png',
          w: 65,
          h: 105,
          anchorX: 32,
          anchorY: 97,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/heavy-punch/2.png',
          w: 67,
          h: 105,
          anchorX: 33,
          anchorY: 97,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/terry/heavy-punch/3.png',
          w: 100,
          h: 105,
          anchorX: 33,
          anchorY: 97,
          durationMs: 180,
        },
        {
          src: 'assets/img/characters/terry/heavy-punch/4.png',
          w: 67,
          h: 105,
          anchorX: 33,
          anchorY: 97,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/terry/heavy-punch/5.png',
          w: 67,
          h: 105,
          anchorX: 33,
          anchorY: 97,
          durationMs: 60,
        },
      ],
    },
    lightKick: {
      frames: [
        {
          src: 'assets/img/characters/terry/light-kick/0.png',
          w: 54,
          h: 108,
          anchorX: 29,
          anchorY: 107,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/light-kick/1.png',
          w: 99,
          h: 105,
          anchorX: 41,
          anchorY: 104,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/light-kick/2.png',
          w: 54,
          h: 108,
          anchorX: 29,
          anchorY: 107,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/light-kick/3.png',
          w: 66,
          h: 101,
          anchorX: 37,
          anchorY: 100,
          durationMs: 80,
        },
      ],
    },
    heavyKick: {
      frames: [
        {
          src: 'assets/img/characters/terry/heavy-kick/0.png',
          w: 55,
          h: 108,
          anchorX: 22,
          anchorY: 107,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/1.png',
          w: 55,
          h: 108,
          anchorX: 22,
          anchorY: 107,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/2.png',
          w: 60,
          h: 108,
          anchorX: 24,
          anchorY: 107,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/3.png',
          w: 64,
          h: 108,
          anchorX: 9,
          anchorY: 107,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/4.png',
          w: 99,
          h: 108,
          anchorX: -6,
          anchorY: 107,
          durationMs: 120,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/5.png',
          w: 64,
          h: 108,
          anchorX: 9,
          anchorY: 107,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/6.png',
          w: 60,
          h: 108,
          anchorX: 24,
          anchorY: 107,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/terry/heavy-kick/7.png',
          w: 55,
          h: 108,
          anchorX: 22,
          anchorY: 107,
          durationMs: 100,
        },
      ],
    },
    victory: {
      frames: [
        {
          src: 'assets/img/characters/terry/victory/0.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/terry/victory/1.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 120,
        },
        {
          src: 'assets/img/characters/terry/victory/2.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 110,
        },
        {
          src: 'assets/img/characters/terry/victory/3.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 110,
        },
        {
          src: 'assets/img/characters/terry/victory/4.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/victory/5.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/victory/6.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 90,
        },
        {
          src: 'assets/img/characters/terry/victory/7.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/terry/victory/8.png',
          w: 75,
          h: 144,
          anchorX: 37,
          anchorY: 138,
          durationMs: 400,
        },
      ],
    },
  };

  protected override readonly specials: readonly SpecialMove[] = [
    {
      name: 'crackShoot',
      motion: ['down', 'left'],
      button: 'lightKick',
      voices: [{ src: 'assets/sfx/terry/terry-crackshoot.mp3', frame: 4 }],
      whiffSrc: 'assets/sfx/misc/special-travel.mp3',
      travelDistancePct: 0.25,
      travelStartFrame: 4,
      travelEndFrame: 7,
      arcHeight: 20,
      frames: { frames: withDurations(CRACK_SHOOT_FRAMES, [40, 40, 50, 60, 100, 100, 80, 180]) },
    },
    {
      name: 'crackShootHeavy',
      motion: ['down', 'left'],
      button: 'heavyKick',
      voices: [{ src: 'assets/sfx/terry/terry-crackshoot.mp3', frame: 4 }],
      whiffSrc: 'assets/sfx/misc/special-travel.mp3',
      travelDistancePct: 0.5,
      travelStartFrame: 4,
      travelEndFrame: 7,
      arcHeight: 40,
      frames: {
        frames: withDurations(CRACK_SHOOT_FRAMES, [80, 120, 120, 140, 170, 170, 140, 180]),
      },
    },
    {
      name: 'burningKnuckle',
      motion: ['down', 'left'],
      button: 'lightPunch',
      voices: [{ src: 'assets/sfx/terry/terry-burning-knuckle.mp3', frame: 6 }],
      whiffSrc: 'assets/sfx/misc/special-travel.mp3',
      travelDistancePct: 0.3,
      travelStartFrame: 6,
      travelEndFrame: 10,
      frames: {
        frames: withDurations(
          BURNING_KNUCKLE_FRAMES,
          [50, 50, 50, 50, 50, 50, 80, 100, 80, 80, 150],
        ),
      },
    },
    {
      name: 'burningKnuckleHeavy',
      motion: ['down', 'left'],
      button: 'heavyPunch',
      voices: [{ src: 'assets/sfx/terry/terry-burning-knuckle.mp3', frame: 6 }],
      whiffSrc: 'assets/sfx/misc/special-travel.mp3',
      travelDistancePct: 0.6,
      travelStartFrame: 6,
      travelEndFrame: 10,
      frames: {
        frames: withDurations(
          BURNING_KNUCKLE_FRAMES,
          [60, 140, 120, 120, 90, 90, 50, 100, 60, 80, 150],
        ),
      },
    },
    {
      name: 'risingTackle',
      motion: ['down', 'up'],
      button: 'lightPunch',
      voices: [{ src: 'assets/sfx/terry/terry-rising-tackle.mp3', frame: 3 }],
      whiffSrc: 'assets/sfx/misc/special-travel.mp3',
      arcHeight: 40,
      travelDistancePct: 0.05,
      travelStartFrame: 3,
      travelEndFrame: 10,
      frames: {
        frames: [
          ...withDurations(RISING_TACKLE_FRAMES.slice(0, 8), [50, 50, 50, 60, 80, 80, 80, 110]),
          { ...RISING_TACKLE_FRAMES[1], durationMs: 150 },
          { src: 'assets/img/characters/terry/jump/4.png', w: 68, h: 136, anchorX: 37, anchorY: 135, durationMs: 150 },
        ],
      },
    },
    {
      name: 'risingTackleHeavy',
      motion: ['down', 'up'],
      button: 'heavyPunch',
      voices: [{ src: 'assets/sfx/terry/terry-rising-tackle.mp3', frame: 3 }],
      whiffSrc: 'assets/sfx/misc/special-travel.mp3',
      arcHeight: 120,
      travelDistancePct: 0.1,
      travelStartFrame: 3,
      travelEndFrame: 10,
      frames: {
        frames: [
          ...withDurations(RISING_TACKLE_FRAMES.slice(0, 8), [60, 140, 140, 80, 100, 100, 100, 130]),
          { ...RISING_TACKLE_FRAMES[1], durationMs: 190 },
          { src: 'assets/img/characters/terry/jump/4.png', w: 68, h: 136, anchorX: 37, anchorY: 135, durationMs: 190 },
        ],
      },
    },
    {
      name: 'powerWave',
      motion: ['down', 'right'],
      button: 'lightPunch',
      voices: [
        { src: 'assets/sfx/terry/terry-power-wave-1.mp3', frame: 0 },
        { src: 'assets/sfx/terry/terry-power-wave-2.mp3', frame: 5 },
      ],
      frames: {
        frames: withDurations(POWER_WAVE_FRAMES, [40, 70, 90, 80, 80, 100, 150]),
      },
      projectile: {
        componentClass: PowerWave,
        spawnFrame: 5,
        spawnOffsetX: 40,
        spawnOffsetY: 0,
      },
    },
    {
      name: 'powerWaveHeavy',
      motion: ['down', 'right'],
      button: 'heavyPunch',
      voices: [
        { src: 'assets/sfx/terry/terry-power-wave-1.mp3', frame: 0 },
        { src: 'assets/sfx/terry/terry-power-wave-2.mp3', frame: 5 },
      ],
      frames: {
        frames: withDurations(POWER_WAVE_FRAMES, [50, 130, 160, 130, 80, 110, 170]),
      },
      projectile: {
        componentClass: PowerWave,
        spawnFrame: 5,
        spawnOffsetX: 40,
        spawnOffsetY: 0,
        speed: 36,
      },
    },
  ];

  protected override readonly bodyAnchorX = 31;

  override async playOutro(): Promise<void> {
    this.scripted.set(true);
    await this.backDash();
    await this.backDash();
    await this.playScriptedClip('victory', {
      voice: { src: 'assets/sfx/terry/terry-ok.mp3', frame: 6 },
      projectile: { componentClass: Hat, spawnFrame: 6, spawnOffsetX: 38, spawnOffsetY: -95 },
      projectileFlightMs: HAT_FLIGHT_MS,
      holdAfterLandMs: 1000,
    });
  }
}
