import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Character } from '../../components/character/character';
import { AnimationData, AnimationName, CharacterVoices } from '../../models/character';

/** Ryo Sakazaki — concrete `Character` subclass (Kyokugen karate, `RyoStage`). */
@Component({
  selector: 'app-ryo',
  templateUrl: '../../components/character/character.html',
  styleUrl: './ryo.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Ryo extends Character {
  protected override readonly spriteBaseHeight = 107;
  protected override readonly bodyAnchorX = 26;

  protected override readonly voices: CharacterVoices = {
    lightPunch: 'assets/sfx/ryo/light-punch.mp3',
    heavyPunch: 'assets/sfx/ryo/heavy-punch.mp3',
    lightKick: 'assets/sfx/ryo/light-punch.mp3',
    heavyKick: 'assets/sfx/ryo/heavy-punch.mp3',
    lightPunchWhiff: 'assets/sfx/misc/light-punch-whiff.mp3',
    heavyPunchWhiff: 'assets/sfx/misc/heavy-punch-whiff.mp3',
    lightKickWhiff: 'assets/sfx/misc/light-punch-whiff.mp3',
    heavyKickWhiff: 'assets/sfx/misc/heavy-punch-whiff.mp3',
    jump: 'assets/sfx/misc/jump.mp3',
  };

  protected override readonly animationFrames: Partial<Record<AnimationName, AnimationData>> = {
    idle: {
      loop: true,
      bounce: true,
      frames: [
        {
          src: 'assets/img/characters/ryo/idle/0.png',
          w: 62,
          h: 103,
          anchorX: 26,
          anchorY: 103,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/ryo/idle/1.png',
          w: 60,
          h: 104,
          anchorX: 26,
          anchorY: 104,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/ryo/idle/2.png',
          w: 58,
          h: 106,
          anchorX: 26,
          anchorY: 106,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/ryo/idle/3.png',
          w: 55,
          h: 107,
          anchorX: 25,
          anchorY: 107,
          durationMs: 150,
        },
      ],
    },
    forward: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/ryo/walk/0.png',
          w: 60,
          h: 104,
          anchorX: 32,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/walk/1.png',
          w: 60,
          h: 103,
          anchorX: 31,
          anchorY: 103,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/walk/2.png',
          w: 56,
          h: 104,
          anchorX: 29,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/walk/3.png',
          w: 60,
          h: 104,
          anchorX: 32,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/walk/4.png',
          w: 57,
          h: 105,
          anchorX: 28,
          anchorY: 105,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/walk/5.png',
          w: 57,
          h: 106,
          anchorX: 28,
          anchorY: 106,
          durationMs: 175,
        },
      ],
    },
    backwards: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/ryo/backwards/0.png',
          w: 53,
          h: 107,
          anchorX: 31,
          anchorY: 107,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/backwards/1.png',
          w: 54,
          h: 106,
          anchorX: 31,
          anchorY: 106,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/backwards/2.png',
          w: 56,
          h: 105,
          anchorX: 32,
          anchorY: 105,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/backwards/3.png',
          w: 54,
          h: 105,
          anchorX: 32,
          anchorY: 105,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/backwards/4.png',
          w: 53,
          h: 104,
          anchorX: 31,
          anchorY: 104,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/ryo/backwards/5.png',
          w: 53,
          h: 105,
          anchorX: 32,
          anchorY: 105,
          durationMs: 175,
        },
      ],
    },
    backstep: {
      frames: [
        {
          src: 'assets/img/characters/ryo/backstep/0.png',
          w: 88,
          h: 94,
          anchorX: 44,
          anchorY: 94,
          durationMs: 380,
        },
        {
          src: 'assets/img/characters/ryo/backstep/1.png',
          w: 76,
          h: 90,
          anchorX: 36,
          anchorY: 90,
          durationMs: 70,
        },
      ],
    },
    lightPunch: {
      frames: [
        {
          src: 'assets/img/characters/ryo/light-punch/0.png',
          w: 54,
          h: 104,
          anchorX: 23,
          anchorY: 104,
          durationMs: 40,
        },
        {
          src: 'assets/img/characters/ryo/light-punch/1.png',
          w: 66,
          h: 104,
          anchorX: 25,
          anchorY: 104,
          durationMs: 45,
        },
        {
          src: 'assets/img/characters/ryo/light-punch/2.png',
          w: 83,
          h: 104,
          anchorX: 22,
          anchorY: 104,
          durationMs: 95,
        },
      ],
    },
    heavyPunch: {
      frames: [
        {
          src: 'assets/img/characters/ryo/heavy-punch/0.png',
          w: 69,
          h: 105,
          anchorX: 28,
          anchorY: 105,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/ryo/heavy-punch/1.png',
          w: 69,
          h: 104,
          anchorX: 35,
          anchorY: 104,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/ryo/heavy-punch/2.png',
          w: 101,
          h: 103,
          anchorX: 38,
          anchorY: 103,
          durationMs: 90,
        },
        {
          src: 'assets/img/characters/ryo/heavy-punch/1.png',
          w: 69,
          h: 104,
          anchorX: 35,
          anchorY: 104,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/ryo/heavy-punch/0.png',
          w: 69,
          h: 105,
          anchorX: 28,
          anchorY: 105,
          durationMs: 60,
        },
      ],
    },
    lightKick: {
      frames: [
        {
          src: 'assets/img/characters/ryo/light-kick/0.png',
          w: 63,
          h: 106,
          anchorX: 27,
          anchorY: 106,
          durationMs: 85,
        },
        {
          src: 'assets/img/characters/ryo/light-kick/1.png',
          w: 57,
          h: 106,
          anchorX: 44,
          anchorY: 106,
          durationMs: 85,
        },
        {
          src: 'assets/img/characters/ryo/light-kick/2.png',
          w: 100,
          h: 103,
          anchorX: 59,
          anchorY: 103,
          durationMs: 160,
        },
        {
          src: 'assets/img/characters/ryo/light-kick/1.png',
          w: 57,
          h: 106,
          anchorX: 44,
          anchorY: 106,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/ryo/light-kick/0.png',
          w: 63,
          h: 106,
          anchorX: 27,
          anchorY: 106,
          durationMs: 60,
        },
      ],
    },
    heavyKick: {
      frames: [
        {
          src: 'assets/img/characters/ryo/heavy-kick/0.png',
          w: 56,
          h: 106,
          anchorX: 32,
          anchorY: 106,
          durationMs: 90,
        },
        {
          src: 'assets/img/characters/ryo/heavy-kick/1.png',
          w: 54,
          h: 106,
          anchorX: 32,
          anchorY: 106,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/ryo/heavy-kick/2.png',
          w: 69,
          h: 101,
          anchorX: 31,
          anchorY: 101,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/ryo/heavy-kick/3.png',
          w: 108,
          h: 106,
          anchorX: 30,
          anchorY: 106,
          durationMs: 160,
        },
        {
          src: 'assets/img/characters/ryo/heavy-kick/4.png',
          w: 52,
          h: 106,
          anchorX: 18,
          anchorY: 106,
          durationMs: 90,
        },
      ],
    },
  };
}
