import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Character } from '../components/character/character';
import { AnimationData, AnimationName } from '../models/character';

/** Joe Higashi — concrete `Character` subclass (Muay Thai fighter, `JoeStage`). */
@Component({
  selector: 'app-joe',
  templateUrl: '../components/character/character.html',
  styleUrl: './joe.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Joe extends Character {
  protected override readonly spriteBaseHeight = 107;
  protected override readonly bodyAnchorX = 26;

  protected override readonly animationFrames: Partial<Record<AnimationName, AnimationData>> = {
    idle: {
      loop: true,
      bounce: true,
      frames: [
        {
          src: 'assets/img/characters/joe/idle/0.png',
          w: 64,
          h: 104,
          anchorX: 27,
          anchorY: 104,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/idle/1.png',
          w: 58,
          h: 106,
          anchorX: 26,
          anchorY: 106,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/idle/2.png',
          w: 56,
          h: 107,
          anchorX: 25,
          anchorY: 107,
          durationMs: 200,
        },
      ],
    },
    forward: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/joe/walk/0.png',
          w: 58,
          h: 107,
          anchorX: 29,
          anchorY: 107,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/walk/1.png',
          w: 53,
          h: 106,
          anchorX: 26,
          anchorY: 106,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/walk/2.png',
          w: 51,
          h: 109,
          anchorX: 25,
          anchorY: 109,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/walk/3.png',
          w: 52,
          h: 108,
          anchorX: 26,
          anchorY: 108,
          durationMs: 175,
        },
      ],
    },
    backwards: {
      loop: true,
      frames: [
        {
          src: 'assets/img/characters/joe/backwards/0.png',
          w: 52,
          h: 108,
          anchorX: 26,
          anchorY: 108,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/backwards/1.png',
          w: 50,
          h: 106,
          anchorX: 25,
          anchorY: 106,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/backwards/2.png',
          w: 51,
          h: 108,
          anchorX: 25,
          anchorY: 108,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/backwards/3.png',
          w: 49,
          h: 109,
          anchorX: 24,
          anchorY: 109,
          durationMs: 175,
        },
        {
          src: 'assets/img/characters/joe/backwards/4.png',
          w: 48,
          h: 109,
          anchorX: 24,
          anchorY: 109,
          durationMs: 175,
        },
      ],
    },
    crouch: {
      frames: [
        {
          src: 'assets/img/characters/joe/crouch/0.png',
          w: 53,
          h: 95,
          anchorX: 21,
          anchorY: 95,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/joe/crouch/1.png',
          w: 58,
          h: 71,
          anchorX: 29,
          anchorY: 71,
          durationMs: 100,
        },
      ],
    },
    crouchStill: {
      frames: [
        {
          src: 'assets/img/characters/joe/crouch/1.png',
          w: 58,
          h: 71,
          anchorX: 29,
          anchorY: 71,
          durationMs: 100,
        },
      ],
    },
    crouchForward: {
      loop: true,
      bounce: true,
      frames: [
        {
          src: 'assets/img/characters/joe/crouch-forward/0.png',
          w: 50,
          h: 71,
          anchorX: 25,
          anchorY: 71,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/crouch-forward/1.png',
          w: 49,
          h: 73,
          anchorX: 24,
          anchorY: 73,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/crouch-forward/2.png',
          w: 45,
          h: 74,
          anchorX: 22,
          anchorY: 74,
          durationMs: 200,
        },
      ],
    },
    jumpUp: {
      frames: [
        {
          src: 'assets/img/characters/joe/jump/0.png',
          w: 38,
          h: 121,
          anchorX: 20,
          anchorY: 121,
          durationMs: 280,
        },
        {
          src: 'assets/img/characters/joe/jump/1.png',
          w: 53,
          h: 81,
          anchorX: 26,
          anchorY: 81,
          durationMs: 150,
        },
      ],
    },
    jumpFall: {
      frames: [
        {
          src: 'assets/img/characters/joe/jump/2.png',
          w: 59,
          h: 124,
          anchorX: 32,
          anchorY: 124,
          durationMs: 150,
        },
      ],
    },
    jumpForward: {
      frames: [
        {
          src: 'assets/img/characters/joe/jump-forward/0.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 280,
        },
        {
          src: 'assets/img/characters/joe/jump-forward/1.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/joe/jump-forward/2.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/joe/jump-forward/3.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 120,
        },
      ],
    },
    jumpForwardFall: {
      frames: [
        {
          src: 'assets/img/characters/joe/jump-forward/fall0.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 150,
        },
      ],
    },
    jumpBackward: {
      frames: [
        {
          src: 'assets/img/characters/joe/jump-backward/0.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 180,
        },
        {
          src: 'assets/img/characters/joe/jump-backward/1.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/joe/jump-backward/2.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 130,
        },
        {
          src: 'assets/img/characters/joe/jump-backward/3.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 130,
        },
      ],
    },
    jumpBackwardFall: {
      frames: [
        {
          src: 'assets/img/characters/joe/jump-backward/fall0.png',
          w: 88,
          h: 130,
          anchorX: 44,
          anchorY: 65,
          durationMs: 150,
        },
      ],
    },
    lightPunch: {
      frames: [
        {
          src: 'assets/img/characters/joe/light-punch/0.png',
          w: 68,
          h: 106,
          anchorX: 24,
          anchorY: 106,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/joe/light-punch/1.png',
          w: 88,
          h: 106,
          anchorX: 24,
          anchorY: 106,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/joe/light-punch/0.png',
          w: 68,
          h: 106,
          anchorX: 24,
          anchorY: 106,
          durationMs: 50,
        },
      ],
    },
    heavyPunch: {
      frames: [
        {
          src: 'assets/img/characters/joe/heavy-punch/0.png',
          w: 64,
          h: 108,
          anchorX: 29,
          anchorY: 108,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/heavy-punch/1.png',
          w: 56,
          h: 106,
          anchorX: 23,
          anchorY: 106,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/heavy-punch/2.png',
          w: 98,
          h: 104,
          anchorX: 24,
          anchorY: 104,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/heavy-punch/1.png',
          w: 56,
          h: 106,
          anchorX: 23,
          anchorY: 106,
          durationMs: 80,
        },
      ],
    },
    lightKick: {
      frames: [
        {
          src: 'assets/img/characters/joe/light-kick/0.png',
          w: 61,
          h: 104,
          anchorX: 12,
          anchorY: 104,
          durationMs: 45,
        },
        {
          src: 'assets/img/characters/joe/light-kick/1.png',
          w: 55,
          h: 106,
          anchorX: 4,
          anchorY: 106,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/joe/light-kick/2.png',
          w: 86,
          h: 109,
          anchorX: -2,
          anchorY: 109,
          durationMs: 150,
        },
        {
          src: 'assets/img/characters/joe/light-kick/1.png',
          w: 55,
          h: 106,
          anchorX: 4,
          anchorY: 106,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/joe/light-kick/0.png',
          w: 61,
          h: 104,
          anchorX: 12,
          anchorY: 104,
          durationMs: 45,
        },
      ],
    },
    heavyKick: {
      frames: [
        {
          src: 'assets/img/characters/joe/heavy-kick/0.png',
          w: 51,
          h: 104,
          anchorX: 22,
          anchorY: 104,
          durationMs: 70,
        },
        {
          src: 'assets/img/characters/joe/heavy-kick/1.png',
          w: 45,
          h: 101,
          anchorX: 14,
          anchorY: 101,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/heavy-kick/2.png',
          w: 63,
          h: 94,
          anchorX: 11,
          anchorY: 94,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/heavy-kick/3.png',
          w: 88,
          h: 106,
          anchorX: 9,
          anchorY: 106,
          durationMs: 160,
        },
        {
          src: 'assets/img/characters/joe/heavy-kick/4.png',
          w: 55,
          h: 106,
          anchorX: 4,
          anchorY: 106,
          durationMs: 100,
        },
        {
          src: 'assets/img/characters/joe/heavy-kick/5.png',
          w: 61,
          h: 104,
          anchorX: 12,
          anchorY: 104,
          durationMs: 120,
        },
      ],
    },
    crouchLightPunch: {
      frames: [
        {
          src: 'assets/img/characters/joe/crouch-light-punch/0.png',
          w: 53,
          h: 74,
          anchorX: 24,
          anchorY: 74,
          durationMs: 50,
        },
        {
          src: 'assets/img/characters/joe/crouch-light-punch/1.png',
          w: 74,
          h: 71,
          anchorX: 24,
          anchorY: 71,
          durationMs: 100,
        },
      ],
    },
    crouchHeavyPunch: {
      frames: [
        {
          src: 'assets/img/characters/joe/crouch-heavy-punch/0.png',
          w: 56,
          h: 70,
          anchorX: 29,
          anchorY: 70,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/crouch-heavy-punch/1.png',
          w: 53,
          h: 69,
          anchorX: 24,
          anchorY: 69,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/crouch-heavy-punch/2.png',
          w: 94,
          h: 65,
          anchorX: 24,
          anchorY: 65,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/crouch-heavy-punch/1.png',
          w: 53,
          h: 69,
          anchorX: 24,
          anchorY: 69,
          durationMs: 80,
        },
      ],
    },
    crouchLightKick: {
      frames: [
        {
          src: 'assets/img/characters/joe/crouch-light-kick/0.png',
          w: 63,
          h: 65,
          anchorX: 39,
          anchorY: 65,
          durationMs: 60,
        },
        {
          src: 'assets/img/characters/joe/crouch-light-kick/1.png',
          w: 87,
          h: 64,
          anchorX: 28,
          anchorY: 64,
          durationMs: 120,
        },
      ],
    },
    crouchHeavyKick: {
      travelDistancePct: 0.05,
      travelStartFrame: 1,
      travelEndFrame: 3,
      frames: [
        {
          src: 'assets/img/characters/joe/crouch-heavy-kick/0.png',
          w: 63,
          h: 65,
          anchorX: 39,
          anchorY: 65,
          durationMs: 80,
        },
        {
          src: 'assets/img/characters/joe/crouch-heavy-kick/1.png',
          w: 58,
          h: 64,
          anchorX: 22,
          anchorY: 64,
          durationMs: 90,
        },
        {
          src: 'assets/img/characters/joe/crouch-heavy-kick/2.png',
          w: 82,
          h: 54,
          anchorX: 25,
          anchorY: 54,
          durationMs: 200,
        },
        {
          src: 'assets/img/characters/joe/crouch-heavy-kick/1.png',
          w: 58,
          h: 64,
          anchorX: 22,
          anchorY: 64,
          durationMs: 100,
        },
      ],
    },
  };
}
